"""Canonical defaults for projects generated by the bootstrap commands.

These values govern generated project metadata. They are deliberately separate
from compliance policy: RSK008 checks the selected build backend, not a
dependency version pin.
"""

DEFAULT_PYTHON_VERSION = "3.12"
DEFAULT_UV_BUILD_REQUIREMENT = "uv_build>=0.12.5,<0.13"
