"""Deterministic renderers for generated policy artifacts."""

from __future__ import annotations

import json

from repo_standard.policy.models import Policy


def render_compiled(policy: Policy) -> str:
    return json.dumps(policy.to_data(), indent=2, sort_keys=True) + "\n"


def render_reference(policy: Policy) -> str:
    lines = [
        "# Policy Reference",
        "",
        "<!-- Generated by scripts/generate_policy.py; do not edit directly. -->",
        "",
        f"Policy schema: `{policy.schema_version}`",
        f"Standard version: `{policy.standard_version}`",
        f"Standard major: `{policy.standard_major}`",
        "",
        "This normative catalogue is generated from `policy/base.yaml` and",
        "`policy/profiles/`. The linked prose explains the policy; executable",
        "values and rule applicability come only from the versioned YAML model.",
        "",
        "## Profiles",
        "",
    ]
    for profile in policy.profiles:
        markers = (
            ", ".join(
                f"`{marker.path}` ({marker.kind})"
                for marker in profile.detection.markers
            )
            or "fallback"
        )
        lines.extend(
            [
                f"### {profile.id}",
                "",
                profile.description,
                "",
                f"Detection priority: `{profile.detection.priority}`; "
                f"markers: {markers}.",
                "",
            ]
        )
    lines.extend(["## Rules", ""])
    for rule in policy.rules:
        lines.extend(
            [
                f"### {rule.id}: {rule.title}",
                "",
                f"- Level: `{rule.level}`",
                f"- Profiles: {', '.join(f'`{profile}`' for profile in rule.profiles)}",
                f"- Source: [`{rule.source.document}` — {rule.source.section}]"
                f"(../{rule.source.document})",
                f"- Enforcement: `{rule.enforcement}`",
                f"- Check kind: `{rule.check.kind}`",
                "",
                f"Rationale: {rule.rationale}",
                "",
                f"Remediation: {rule.remediation}",
                "",
            ]
        )
    if policy.retired_rule_ids:
        lines.extend(
            [
                "## Retired Rule IDs",
                "",
                ", ".join(f"`{rule_id}`" for rule_id in policy.retired_rule_ids),
                "",
            ]
        )
    return "\n".join(lines)
